### ISSUE TITLE
Won't compile on Stable Rustc 1.20.0 nor 1.21.0 because of card_validate

### ISSUE THREAD

**Issue by greglearns** [Keats/validator#35]
```
Compiling card-validate v2.1.2
error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/greg/.cargo/registry/src/github.com-1ecc6299db9ec823/card-validate-2.1.2/src/lib.rs:4:1
  |
4 | #![feature(inclusive_range, range_contains)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Looks like one of validator's dependencies, card_validate, cannot compile on Stable Rust. What's the best way to fix this?

**Comment by valeriansaliou** [comment]
Hey there!

`valeriansaliou/rs-card-validate` uses Rust ranges, which work on nightly but not on stable. It should be easy to fix, I'm working on it, will PR validator w/ the update.

**Comment by valeriansaliou** [comment]
Bumped `rs-card-validate` to [06a7c5fa95173cf421888f9df6edc3e5d4519947](https://github.com/valeriansaliou/rs-card-validate/commit/06a7c5fa95173cf421888f9df6edc3e5d4519947).

@greglearns semver patch, so you only need to `cargo update` in your project.

**Comment by Keats** [comment]
I don't see 2.1.3 on crates.io yet. 2.1.2 should probably be yanked too

**Comment by valeriansaliou** [comment]
Can you check again? Should be on Crates.io now.

**Comment by Keats** [comment]
Thanks!

**Comment by greglearns** [comment]
Thank you!
