### ISSUE TITLE
error: Unexpected validator: phone

### ISSUE THREAD

**Issue by RemiKalbe** [Keats/validator#124]
```rust
#[macro_use]
extern crate validator;
```
```rust
use validator::{Validate, ValidationError};

#[derive(Validate)]
pub struct User {
    ...
    #[validate(phone)]
    pub phone_number: Option<String>,
    ...
}
```
```
error: Unexpected validator: phone
 --> src/path/to/file
  |
9 |     #[validate(phone)]
  |                ^^^^^
```
My Cargo.toml file
```toml
validator = { version = "0.11", features = ["derive", "phone"] }
```

**Comment by RemiKalbe** [comment]
On top of that I have a very strange error
```
error[E0308]: mismatched types
 --> path/to/file
  |
7 | #[derive(Validate)]
  |          ^^^^^^^^
  |          |
  |          expected struct `std::string::String`, found `&std::string::String`
  |          help: try using a conversion method: `(Validate).to_string()`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by nikandlv** [comment]
Same issue here

**Comment by xFrednet** [comment]
I could replicate the first error on the current version and the git repo it self. The problem seems to be the same for other optional features like the `credit_card` validation. It only happens when I use the create via `Cargo.toml` the test are all running fine. It also worked in version `0.10` where the `validator` and `validator_derive` crates where still imported separately.

The error probably originates from [`validator_derive::lib.rs` line 319](https://github.com/Keats/validator/blob/07a477eb6e45e232badc89628fa3243230945bfa/validator_derive/src/lib.rs#L319)

```rust
// Line 287
#[cfg(feature = "phone")]
"phone" => {
    assert_string_type("phone", field_type, &field.ty);
    validators.push(FieldValidation::new(Validator::Phone));
}
[...]
// Line 316
_ => {
    let mut ident = proc_macro2::TokenStream::new();
    name.to_tokens(&mut ident);
    abort!(name.span(), "Unexpected validator: {}", ident)
}
```

It might be the case that the cfg feature isn't forwarded from the `validator` to the `validate_derive` crate but I'm not sure. 

## Working test for version `0.10`

Cargo.toml
```toml
[dependencies]
validator = "0.10"
validator_derive = {version = "0.10", features = ["phone"] }
```

main.rs
```rust
#[macro_use]
extern crate validator_derive;
extern crate validator;
use validator::{Validate, ValidationError};


#[derive(Debug, Validate)]
struct TestStruct {
    #[validate(phone)]
    val: String,
}

fn main() {
    let test = TestStruct {val: "Hello World".to_string()};

    test.validate().unwrap_err();

    println!("Hello World");
}

```

---

## Test of newer version `0.11` and higher:

Cargo.toml version 0.11
```toml
[dependencies]
validator = { version="0.11.0", features = ["derive", "phone", "card"] } 
```

Cargo.toml current git
```toml
[dependencies]
validator = { git = "https://github.com/Keats/validator.git", features = ["derive", "phone", "card"] } 
```

main.rs
```rust
use validator::Validate;

#[derive(Debug, Validate)]
struct TestStruct {
    #[validate(phone)]
    val: String,
}

fn main() {
    let test = TestStruct {val: "Hello World".to_string()};
    test.validate().unwrap_err();

    println!("Hello World");
}
```

**Comment by Keats** [comment]
It should be fixed in the last commit of https://github.com/Keats/validator/pull/133

**Comment by xFrednet** [comment]
Yup, it's fixed on the `next` branch 👍

**Comment by Keats** [comment]
Fixed in 0.12
